### ISSUE TITLE
Menu Redesign

### ISSUE THREAD

**Issue by CameronRWest** [quaternionmedia/alfred#74]
- [x] Add title to website
- [x] Change logo to be Home link 
- [x] Add Menu Bar that remains on top of window
- [x] Create function to see which page is active and set link in menu bar as such
- [x] Move MenuItem class name to menu bar links rather than link itself
- [x] Add NavButton that hides based on window size
- [x] Create NavLinks with special class to design separately in css
- [x] Update logo

**Comment by CameronRWest** [comment]
@mrharpo To avoid adding an image folder and images to git repo, where should images be stored and accessed?
And do we leave logo type images in the repo?

**Comment by mrharpo** [comment]
@CameronRWest Currently, everything is just in the `website/src/` folder, logos included. Let's split those into a `website/static/` or `website/assets/` folder instead.

Logos and icons that are part of the interface should be committed (e.g. `al.svg`, `content-cut.svg`, etc), and all regular media (videos, images, etc) are loaded as data passed in from the API.
